import React, { createContext, useContext, useState } from 'react';

interface LanguageContextType {
  language: 'en' | 'tr';
  setLanguage: (lang: 'en' | 'tr') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.reservation': 'Reservation',
    'nav.membership': 'Membership',
    'nav.events': 'Events',
    'nav.admin': 'Admin',
    'nav.profile': 'Profile',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    
    // Entry Page
    'entry.title': 'MMBR',
    'entry.subtitle': 'ARE YOU READY FOR THE NIGHT?',
    'entry.loading': 'Loading video...',
    'entry.scrollDown': 'Scroll down',
    'entry.welcome': 'Welcome',
    'entry.welcomeMessage': 'Step into the MMBR world',
    'entry.startExploring': 'Start Exploring',
    
    // Home Page
    'home.hero.title': 'Welcome to MMBR',
    'home.hero.subtitle': 'The Ultimate Nightlife Experience',
    'home.about.title': 'About Us',
    'home.about.story': 'MMBR Story',
    'home.about.description1': 'MMBR is an exclusive membership-based social club established to bring a new standard to Ankara\'s nightlife. From its architecture to music, from guest profile to service approach, every detail is designed with a focus on quality, privacy and experience.',
    'home.about.description2': 'At MMBR, the goal is not just to entertain; it is to bring together people who share the same vision, the same frequency and the same lifestyle. With international DJs, special performances and carefully curated events; every night offers an unrepeatable experience.',
    'home.about.description3': 'MMBR is where the right crowd is, not the big crowd.',
    'home.stats.experience': 'Years Experience',
    'home.stats.guests': 'Happy Guests',
    'home.stats.events': 'Events Organized',
    'home.stats.djs': 'World Class DJs',
    'home.features.title': 'Why MMBR?',
    'home.features.subtitle': 'Special features that set MMBR apart from other venues',
    'home.features.worldDjs': 'World-Class DJs',
    'home.features.worldDjsDesc': 'Unforgettable music experience with the best international and local DJs',
    'home.features.premiumService': 'Premium Service',
    'home.features.premiumServiceDesc': 'Personalized service approach with our professional team',
    'home.features.qualityGuarantee': 'Quality Guarantee',
    'home.features.qualityGuaranteeDesc': 'High-quality sound system and special lighting technology',
    'home.features.entertainment': '7/24 Entertainment',
    'home.features.entertainmentDesc': 'Continuous entertainment program on weekdays and weekends',
    'home.features.list1': 'Exclusive guest profile with membership system',
    'home.features.list2': 'Not the crowd, but the right energy',
    'home.features.list3': 'International standard music and production',
    'home.features.list4': 'Privacy, comfort and quality-focused approach',
    'home.features.list5': 'A unique nightclub concept in Ankara',
    'home.contact.title': 'Contact',
    'home.contact.description': 'Get in touch with us for your questions, reservation requests, or special event plans.',
    'home.contact.sendMessage': 'Send Message',
    'home.hours.title': 'Operating Hours',
    'home.hours.subtitle': 'Join us for unforgettable nights on Fridays and Saturdays',
    'home.hours.friday': 'Friday',
    'home.hours.fridayTime': '23:00 - 03:00',
    'home.hours.saturday': 'Saturday',
    'home.hours.saturdayTime': '23:00 - 03:00',
    'home.hours.specialNight': 'Special Events Night',
    'home.hours.mainEvent': 'Main Party Night',
    'home.hours.important': 'Important Information',
    'home.hours.reservationAdvice': 'Advance reservations recommended',
    'home.hours.dressCode': 'Smart dress code required',
    'home.hours.minimumAge': 'Minimum age 21 for entry',
    'home.hours.makeReservation': 'Make Reservation',
    
    // Event Rules & Reservation Info
    'home.rules.title': 'Event Rules & Reservation Information',
    'home.rules.rule1': 'Gender balance is observed at entrances.',
    'home.rules.rule2': 'Smart Casual dress code is enforced.',
    'home.rules.rule3': 'Attitude, attire, and general suitability are evaluated; entry may be refused for those deemed unsuitable.',
    'home.rules.rule4': 'Except for those who have paid a deposit, reservations are at 23:30 and will be canceled after 30 minutes.',
    'home.rules.rule5': 'Audio and video recordings are made at the venue and may be used for promotional purposes.',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with us',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.form.namePlaceholder': 'Enter your full name',
    'contact.form.emailPlaceholder': 'Enter your email address',
    'contact.form.phonePlaceholder': 'Enter your phone number',
    'contact.form.subjectPlaceholder': 'Enter subject',
    'contact.form.messagePlaceholder': 'Write your message here...',
    'contact.success': 'Your message has been sent successfully! We will get back to you as soon as possible.',
    'contact.error': 'An error occurred while sending the message. Please try again.',
    
    // About Page
    'about.title': 'About MMBR',
    'about.subtitle': 'Discover our story and vision',
    'about.story.title': 'Our Story',
    'about.story.content': 'Founded in 2015, MMBR has quickly become the premier nightlife destination in the city. Our commitment to excellence and innovation has made us a leader in the entertainment industry.',
    'about.mission.title': 'Our Mission',
    'about.mission.content': 'To create unforgettable experiences through music, bringing people together and fostering a community of night owls who appreciate quality entertainment.',
    'about.vision.title': 'Our Vision',
    'about.vision.content': 'To be the global standard for nightlife entertainment, setting trends and inspiring the next generation of club experiences.',
    
    // Reservation Page
    'reservation.title': 'Make a Reservation',
    'reservation.subtitle': 'Book your table for an unforgettable night',
    'reservation.form.date': 'Date',
    'reservation.form.time': 'Time',
    'reservation.form.guests': 'Number of Guests',
    'reservation.form.table': 'Table Type',
    'reservation.form.name': 'Name',
    'reservation.form.email': 'Email',
    'reservation.form.phone': 'Phone',
    'reservation.form.notes': 'Special Requests',
    'reservation.form.submit': 'Book Now',
    'reservation.tables.regular': 'Regular Table',
    'reservation.tables.vip': 'VIP Table',
    'reservation.tables.booth': 'Private Booth',
    'reservation.success': 'Your reservation has been submitted successfully! We will confirm your booking shortly.',
    'reservation.error': 'An error occurred while making the reservation. Please try again.',
    'reservation.operatingDays': '💡 Our nightclub is open only on Fridays and Saturdays',
    'reservation.operatingInfo': 'Operating Hours & Days',
    'reservation.operatingHours': 'Operating Hours',
    'reservation.invalidDate': 'Our nightclub is open only on Fridays and Saturdays',
    'reservation.selectValidDate': 'Please select a valid date.',
    'reservation.suggestedDate': 'Suggested date: {dayName}, {dateStr}',
    // General Entry
    'reservation.generalEntry': 'General Entry',
    'reservation.generalEntryDesc': 'Make a reservation without choosing a table from the options below',
    'reservation.standingReservation': 'Standing Reservation',
    'reservation.standingDesc': 'Entry reservation without a table',
    'reservation.specialTable': 'Special Table',
    'reservation.specialTableDesc': 'Daily special table reservation',
    'reservation.capacity': 'Capacity:',
    'reservation.price': 'Price:',
    'reservation.status': 'Status:',
    'reservation.capacityFull': 'Capacity Full',
    'reservation.reservedForDate': 'Reserved for This Date',
    'reservation.available': 'Available',
    'reservation.reserved': 'Reserved',
    'reservation.selectDateFirst': 'Please select a date first',
    'reservation.standingCapacityFull': 'Standing reservation capacity full (20/20)',
    'reservation.specialTableTaken': 'Special table is already reserved for this date',
    'reservation.standingSelected': 'Standing reservation selected',
    'reservation.specialSelected': 'Special table reservation selected',
    'reservation.selectTableOrEntry': 'Please select a table or entry type',
    'reservation.selectDate': 'Please select a date',
    'reservation.tableSelection': 'Table Selection',
    'reservation.exploreTablesHint': '🎯 Click on areas on the floor plan to discover tables',
    'reservation.occupied': 'OCCUPIED',
    'reservation.tableOccupiedAtDateTime': 'This table is occupied at the selected date and time',
    'reservation.tableSelected': '{tableName} selected! Fill in your reservation details.',
    'reservation.tableOccupied': 'This table is occupied. Please choose another table.',
    'reservation.tableOccupiedDetail': '{tableName} is occupied on {date} at {time}. Please choose a different table or time.',
    'reservation.standingCapacityFullDetail': 'Standing reservation capacity full (20/20)',
    'reservation.specialTableTakenDetail': 'Special table is already reserved for this date',
    
    // Calendar
    'calendar.today': 'Today',
    'calendar.selectWeekend': 'Select Weekend Date',
    'calendar.onlyWeekends': 'Only weekends available',
    
    // Membership Page
    'membership.title': 'Membership Plans',
    'membership.subtitle': 'Open the doors to privileged experiences at Mmbr. Take advantage of premium membership benefits and take nightlife to the top.',
    'membership.form.title': 'Membership Application',
    'membership.form.selectedPlan': 'Selected plan:',
    'membership.form.name': 'Full Name',
    'membership.form.namePlaceholder': 'Enter your full name',
    'membership.form.email': 'Email',
    'membership.form.emailPlaceholder': 'Enter your email address',
    'membership.form.phone': 'Phone',
    'membership.form.phonePlaceholder': 'Enter your phone number',
    'membership.form.instagram': 'Instagram Profile Link',
    'membership.form.instagramPlaceholder': 'https://instagram.com/username',
    'membership.form.referenceCode': 'Reference Code',
    'membership.form.referenceCodePlaceholder': 'Enter your reference code',
    'membership.form.birthDate': 'Date of Birth',
    'membership.form.summary': 'Membership Summary',
    'membership.form.plan': 'Plan:',
    'membership.form.monthlyFee': 'Monthly Fee:',
    'membership.form.startDate': 'Start Date:',
    'membership.form.note': '* After completing your membership application, you will be redirected to the payment page. Your membership will be activated after your payment is completed.',
    'membership.form.submit': 'Complete Membership Application',
    'membership.bronze.title': 'Silver',
    'membership.bronze.price': '199',
    'membership.bronze.period': 'monthly',
    'membership.bronze.feature1': 'Priority on reservations',
    'membership.bronze.feature2': '10% discount on spending limits',
    'membership.bronze.feature3': '5% discount on Le Porte Restaurant expenses',
    'membership.silver.title': 'Gold',
    'membership.silver.price': '349',
    'membership.silver.period': 'monthly',
    'membership.silver.popular': 'Most Popular',
    'membership.silver.feature1': 'Privileged access to the MMBR world',
    'membership.silver.feature2': 'VIP area access',
    'membership.silver.feature3': 'Priority on reservations',
    'membership.silver.feature4': 'Special advantages at selected events',
    'membership.silver.feature5': 'Exclusive announcements and content for members',
    'membership.silver.feature6': '20% discount on spending limits',
    'membership.silver.feature7': '10% discount on Le Porte Restaurant expenses',
    'membership.gold.title': 'Diamond',
    'membership.gold.price': '599',
    'membership.gold.period': 'monthly',
    'membership.gold.feature1': 'MMBR\'s highest level membership status',
    'membership.gold.feature2': 'Priority entry and reservation rights',
    'membership.gold.feature3': 'Free VIP transfer from home to MMBR and back',
    'membership.gold.feature4': 'Photo opportunity with visiting DJs',
    'membership.gold.feature5': 'Direct contact with personal representative',
    'membership.gold.feature6': 'VIP area access',
    'membership.gold.feature7': 'Priority for special tables and locations',
    'membership.gold.feature8': 'Special pricing at events',
    'membership.gold.feature9': 'Exclusive access to surprise performances and private invitations',
    'membership.gold.feature10': 'Personal concierge / reservation priority',
    'membership.gold.feature11': '30% discount on spending limits',
    'membership.gold.feature12': 'Free participation in Aura Entertainment events',
    'membership.gold.feature13': '20% discount on Le Porte Restaurant expenses',
    'membership.selectPlan': 'Start Membership',
    'membership.selected': 'Selected ✓',
    'membership.benefits.title': 'Member Benefits',
    'membership.benefits.subtitle': 'Discover the special benefits prepared for Mmbr members',
    'membership.benefits.reservation': 'Priority Reservation',
    'membership.benefits.reservationDesc': 'You can reserve the best tables with priority',
    'membership.benefits.events': 'Special Events',
    'membership.benefits.eventsDesc': 'You can participate in events exclusive to members only',
    'membership.benefits.discounts': 'Discounted Prices',
    'membership.benefits.discountsDesc': 'Special member discount on all drinks and food',
    'membership.benefits.vip': 'VIP Service',
    'membership.benefits.vipDesc': 'Personal account manager and premium service',
    'membership.success': '{planName} membership application received! Redirecting to payment page.',
    'membership.error': 'An error occurred while submitting the membership application. Please try again.',
    'membership.selectPlanError': 'Please select a membership plan.',
    
    // Events Page
    'events.title': 'Upcoming Events',
    'events.subtitle': 'Don\'t miss our exciting events',
    'events.viewDetails': 'View Details',
    'events.makeReservation': 'Make Reservation',
    'events.noEvents': 'No upcoming events',
    'events.artist': 'Artist',
    'events.genre': 'Genre',
    'events.duration': 'Duration',
    'events.close': 'Close',
    'events.hours': 'Hours',
    
    // Event Descriptions
    'events.mahmutOrhan.desc': 'Experience an unforgettable night with world-renowned DJ Mahmut Orhan. Get ready to dance to the best examples of deep house and electronic music in MMBR\'s unique atmosphere.',
    'events.deepHouse.desc': 'A night full of the finest examples of deep house music. Take a journey into the depths of music in our underground hall with the best DJs.',
    'events.technoRevolution.desc': 'A night full of revolutionary sounds of techno music. Experience the fusion of technology and music with powerful beats and hypnotic melodies.',
    'events.electronicVibes.desc': 'A special electronic music experience in our VIP Lounge. Experience the most sophisticated form of electronic music at this special night prepared for distinguished guests.',
    'events.underground.desc': 'Discover the most underground sounds in the dark and mysterious atmosphere of the underground. You will experience the most intimate form of alternative electronic music this special night.',
    'events.ibiza.desc': 'Experience the magical atmosphere of Ibiza at MMBR. Enjoy unforgettable moments with balearic beats and sunset vibes at this special night with Mediterranean vibes.',
    'events.minimal.desc': 'Discover the perfect balance of simplicity and complexity at this special night combining the power of minimalism with the energy of techno. An experience where every beat has meaning.',
    'events.progressive.desc': 'Embark on a mesmerizing journey of progressive house music. You will experience a musical odyssey in this night full of melodic structures and powerful rhythms.',
    
    // Admin Page
    'admin.title': 'Admin Dashboard',
    'admin.reservations': 'Reservations',
    'admin.messages': 'Messages',
    'admin.events': 'Events',
    'admin.users': 'Users',
    
    // Profile Page
    'profile.title': 'My Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.reservations': 'My Reservations',
    'profile.activeReservations': 'Active Reservations',
    'profile.pastReservations': 'Past Reservations',
    'profile.noActiveReservations': 'No active reservations.',
    'profile.noPastReservations': 'No past reservations.',
    'profile.membership': 'Membership Status',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.submit': 'Submit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    
    // Footer
    'footer.copyright': '© 2024 MMBR. All rights reserved.',
    'footer.social': 'Follow us on social media',
  },
  tr: {
    // Navigation
    'nav.home': 'Ana Sayfa',
    'nav.about': 'Hakkımızda',
    'nav.contact': 'İletişim',
    'nav.reservation': 'Rezervasyon',
    'nav.membership': 'Üyelik',
    'nav.events': 'Etkinlikler',
    'nav.admin': 'Admin',
    'nav.profile': 'Profil',
    'nav.login': 'Giriş',
    'nav.logout': 'Çıkış',
    
    // Entry Page
    'entry.title': 'MMBR',
    'entry.subtitle': 'GECEYE HAZIR MISINIZ?',
    'entry.loading': 'Video yükleniyor...',
    'entry.scrollDown': 'Aşağı kaydırın',
    'entry.welcome': 'Hoş Geldiniz',
    'entry.welcomeMessage': 'MMBR dünyasına adım atın',
    'entry.startExploring': 'Keşfetmeye Başlayın',
    
    // Home Page
    'home.hero.title': 'MMBR\'e Hoş Geldiniz',
    'home.hero.subtitle': 'Eşsiz Gece Hayatı Deneyimi',
    'home.about.title': 'Hakkımızda',
    'home.about.story': 'MMBR Hikayesi',
    'home.about.description1': 'MMBR, Ankara gece hayatına yeni bir standart getirmek için kurulmuş, üyelik temelli seçkin bir sosyal kulüptür. Mimarisinden müziğine, misafir profilinden servis anlayışına kadar her detay; kalite, gizlilik ve deneyim odaklı olarak tasarlanmıştır.',
    'home.about.description2': 'MMBR\'da amaç sadece eğlenmek değil; aynı vizyonu, aynı frekansı ve aynı yaşam tarzını paylaşan insanları bir araya getirmektir. Uluslararası DJ\'ler, özel performanslar ve özenle kürate edilmiş etkinliklerle; her gece tekrar edilemez bir deneyim sunar.',
    'home.about.description3': 'MMBR, kalabalığın değil doğru kitlenin olduğu yerdir.',
    'home.stats.experience': 'Yıl Deneyim',
    'home.stats.guests': 'Mutlu Misafir',
    'home.stats.events': 'Event Düzenlendi',
    'home.stats.djs': 'World Class DJ',
    'home.features.title': 'Neden MMBR?',
    'home.features.subtitle': 'MMBR\'ı diğer mekanlardan ayıran özel özellikler',
    'home.features.worldDjs': 'Dünya Çapında DJ\'ler',
    'home.features.worldDjsDesc': 'En iyi international ve local DJ\'lerle unutulmaz müzik deneyimi',
    'home.features.premiumService': 'Premium Hizmet',
    'home.features.premiumServiceDesc': 'Profesyonel ekibimizle size özel hizmet anlayışı',
    'home.features.qualityGuarantee': 'Kalite Garantisi',
    'home.features.qualityGuaranteeDesc': 'Yüksek kaliteli ses sistemi ve özel lighting teknolojisi',
    'home.features.entertainment': '7/24 Eğlence',
    'home.features.entertainmentDesc': 'Hafta içi ve hafta sonu kesintisiz eğlence programı',
    'home.features.list1': 'Üyelik sistemi ile seçkin misafir profili',
    'home.features.list2': 'Kalabalık değil, doğru enerji',
    'home.features.list3': 'Uluslararası standartlarda müzik ve prodüksiyon',
    'home.features.list4': 'Gizlilik, konfor ve kalite odaklı yaklaşım',
    'home.features.list5': 'Ankara\'da benzersiz bir gece kulübü konsepti',
    'home.contact.title': 'İletişim',
    'home.contact.description': 'Sorularınız, rezervasyon talepleriniz veya özel etkinlik planlarınız için bizimle iletişime geçin.',
    'home.contact.sendMessage': 'Mesaj Gönder',
    'home.hours.title': 'Çalışma Saatleri',
    'home.hours.subtitle': 'Cuma ve Cumartesi gecelerinde unutulmaz anlara katılın',
    'home.hours.friday': 'Cuma',
    'home.hours.fridayTime': '23:00 - 03:00',
    'home.hours.saturday': 'Cumartesi',
    'home.hours.saturdayTime': '23:00 - 03:00',
    'home.hours.specialNight': 'Özel Etkinlik Gecesi',
    'home.hours.mainEvent': 'Ana Parti Gecesi',
    'home.hours.important': 'Önemli Bilgiler',
    'home.hours.reservationAdvice': 'Önceden rezervasyon önerilir',
    'home.hours.dressCode': 'Şık giyim zorunlu',
    'home.hours.minimumAge': 'Giriş için minimum 21 yaş',
    'home.hours.makeReservation': 'Rezervasyon Yap',
    
    // Event Rules & Reservation Info
    'home.rules.title': 'Etkinlik Kuralları & Rezervasyon Bilgileri',
    'home.rules.rule1': 'Girişlerde cinsiyet dengesi gözlemlenir.',
    'home.rules.rule2': 'Smart Casual giyim kuralı uygulanır.',
    'home.rules.rule3': 'Davranış, giyim ve genel uygunluk değerlendirilir; uygun bulunmayanlar girişi reddedilebilir.',
    'home.rules.rule4': 'Depozito ödememiş kişiler için rezervasyonlar 23:30\'da yapılır ve 30 dakika sonra iptal edilir.',
    'home.rules.rule5': 'Yerleşke içinde ses ve video kayıtları yapılır ve promosyon amaçlı kullanılabilir.',
    
    // Contact Page
    'contact.title': 'İletişim',
    'contact.subtitle': 'Bizimle iletişime geçin',
    'contact.form.name': 'Ad-Soyad',
    'contact.form.email': 'E-posta',
    'contact.form.phone': 'Telefon',
    'contact.form.subject': 'Konu',
    'contact.form.message': 'Mesaj',
    'contact.form.submit': 'Mesaj Gönder',
    'contact.form.namePlaceholder': 'Adınızı ve soyadınızı girin',
    'contact.form.emailPlaceholder': 'E-posta adresinizi girin',
    'contact.form.phonePlaceholder': 'Telefon numaranızı girin',
    'contact.form.subjectPlaceholder': 'Konuyu girin',
    'contact.form.messagePlaceholder': 'Mesajınızı buraya yazın...',
    'contact.success': 'Mesajınız başarıyla gönderildi! En kısa sürede size dönüş yapacağız.',
    'contact.error': 'Mesaj gönderilirken bir hata oluştu. Lütfen tekrar deneyin.',
    
    // About Page
    'about.title': 'MMBR Hakkında',
    'about.subtitle': 'Hikayemizi ve vizyonumuzu keşfedin',
    'about.story.title': 'Hikayemiz',
    'about.story.content': '2015 yılında kurulan MMBR, kısa sürede şehrin önde gelen gece hayatı destinasyonu haline geldi. Mükemmellik ve yenilik konusundaki kararlılığımız bizi eğlence sektöründe lider konuma getirdi.',
    'about.mission.title': 'Misyonumuz',
    'about.mission.content': 'Müzik aracılığıyla unutulmaz deneyimler yaratmak, insanları bir araya getirmek ve kaliteli eğlenceyi takdir eden gece kuşları topluluğunu beslemek.',
    'about.vision.title': 'Vizyonumuz',
    'about.vision.content': 'Gece hayatı eğlencesi için küresel standart olmak, trendleri belirlemek ve gelecek nesil kulüp deneyimlerine ilham vermek.',
    
    // Reservation Page
    'reservation.title': 'Rezervasyon Yap',
    'reservation.subtitle': 'Unutulmaz bir gece için masanızı ayırtın',
    'reservation.form.date': 'Tarih',
    'reservation.form.time': 'Saat',
    'reservation.form.guests': 'Misafir Sayısı',
    'reservation.form.table': 'Masa Türü',
    'reservation.form.name': 'Ad-Soyad',
    'reservation.form.email': 'E-posta',
    'reservation.form.phone': 'Telefon',
    'reservation.form.notes': 'Özel İstekler',
    'reservation.form.submit': 'Rezervasyon Yap',
    'reservation.tables.regular': 'Normal Masa',
    'reservation.tables.vip': 'VIP Masa',
    'reservation.tables.booth': 'Özel Kabin',
    'reservation.success': 'Rezervasyonunuz başarıyla alındı! Kısa sürede onay için size dönüş yapacağız.',
    'reservation.error': 'Rezervasyon yapılırken bir hata oluştu. Lütfen tekrar deneyin.',
    'reservation.operatingDays': '💡 Gece kulübümüz sadece Cuma ve Cumartesi günleri açıktır',
    'reservation.operatingInfo': 'Çalışma Saatleri ve Günler',
    'reservation.operatingHours': 'Çalışma Saatleri',
    'reservation.invalidDate': 'Gece kulübümüz sadece Cuma ve Cumartesi günleri açıktır',
    'reservation.selectValidDate': 'Lütfen uygun bir tarih seçiniz.',
    'reservation.suggestedDate': 'Önerilen tarih: {dayName}, {dateStr}',
    // General Entry
    'reservation.generalEntry': 'Genel Giriş',
    'reservation.generalEntryDesc': 'Aşağıdaki seçeneklerden bir masa seçmeden rezervasyon yapın',
    'reservation.standingReservation': 'Ayakta Rezervasyon',
    'reservation.standingDesc': 'Masa olmadan giriş rezervasyonu',
    'reservation.specialTable': 'Özel Masa',
    'reservation.specialTableDesc': 'Günlük özel masa rezervasyonu',
    'reservation.capacity': 'Kapasite:',
    'reservation.price': 'Fiyat:',
    'reservation.status': 'Durum:',
    'reservation.capacityFull': 'Kapasite Dolu',
    'reservation.reservedForDate': 'Bu Tarih İçin Rezerve Edilmiş',
    'reservation.available': 'Müsait',
    'reservation.reserved': 'Rezerve Edilmiş',
    'reservation.selectDateFirst': 'Lütfen önce bir tarih seçin',
    'reservation.standingCapacityFull': 'Ayakta rezervasyon kapasitesi dolu (20/20)',
    'reservation.specialTableTaken': 'Bu tarih için özel masa zaten rezerve edilmiş',
    'reservation.standingSelected': 'Ayakta rezervasyon seçildi',
    'reservation.specialSelected': 'Özel masa rezervasyonu seçildi',
    'reservation.selectTableOrEntry': 'Lütfen bir masa veya giriş türü seçin',
    'reservation.selectDate': 'Lütfen bir tarih seçin',
    'reservation.tableSelection': 'Masa Seçimi',
    'reservation.exploreTablesHint': '🎯 Zemin planında alanlara tıklayarak masaları keşfedin',
    'reservation.occupied': 'DOLU',
    'reservation.tableOccupiedAtDateTime': 'Bu masa seçilen tarih ve saatte doludur',
    'reservation.tableSelected': '{tableName} seçildi! Rezervasyon detaylarınızı doldurun.',
    'reservation.tableOccupied': 'Bu masa doludur. Lütfen başka bir masa seçin.',
    'reservation.tableOccupiedDetail': '{tableName}, {date} tarihinde {time} saatinde doludur. Lütfen farklı bir masa veya saat seçin.',
    'reservation.standingCapacityFullDetail': 'Ayakta rezervasyon kapasitesi dolu (20/20)',
    'reservation.specialTableTakenDetail': 'Bu tarih için özel masa zaten rezerve edilmiş',
    
    // Calendar
    'calendar.today': 'Bugün',
    'calendar.selectWeekend': 'Hafta Sonu Tarihi Seç',
    'calendar.onlyWeekends': 'Sadece hafta sonları müsait',
    
    // Membership Page
    'membership.title': 'Üyelik Planları',
    'membership.subtitle': 'Mmbr\'da ayrıcalıklı deneyimlerin kapısını aralayın. Premium üyelik avantajlarından yararlanın ve gece hayatını zirveye taşıyın.',
    'membership.form.title': 'Üyelik Başvurusu',
    'membership.form.selectedPlan': 'Seçtiğiniz plan:',
    'membership.form.name': 'Ad Soyad',
    'membership.form.namePlaceholder': 'Adınızı ve soyadınızı girin',
    'membership.form.email': 'E-posta',
    'membership.form.emailPlaceholder': 'E-posta adresinizi girin',
    'membership.form.phone': 'Telefon',
    'membership.form.phonePlaceholder': 'Telefon numaranızı girin',
    'membership.form.instagram': 'Instagram Profil Linki',
    'membership.form.instagramPlaceholder': 'https://instagram.com/kullaniciadi',
    'membership.form.referenceCode': 'Referans Kodu',
    'membership.form.referenceCodePlaceholder': 'Referans kodunuz girin',
    'membership.form.birthDate': 'Doğum Tarihi',
    'membership.form.summary': 'Üyelik Özeti',
    'membership.form.plan': 'Plan:',
    'membership.form.monthlyFee': 'Aylık Ücret:',
    'membership.form.startDate': 'Başlangıç Tarihi:',
    'membership.form.note': '* Üyelik başvurunuzu tamamladıktan sonra, ödeme sayfasına yönlendirileceksiniz. Üyeliğiniz ödeme işleminiz tamamlandıktan sonra aktif hale gelecektir.',
    'membership.form.submit': 'Üyelik Başvurusunu Tamamla',
    'membership.bronze.title': 'Silver',
    'membership.bronze.price': '199',
    'membership.bronze.period': 'aylık',
    'membership.bronze.feature1': 'Rezervasyon önceliği',
    'membership.bronze.feature2': 'Harcamalar limitinde 10% indirim',
    'membership.bronze.feature3': 'Le Porte Restaurant harcamalarında 5% indirim',
    'membership.silver.title': 'Gold',
    'membership.silver.price': '349',
    'membership.silver.period': 'aylık',
    'membership.silver.popular': 'En Popüler',
    'membership.silver.feature1': 'MMBR dünyasına ayrıcalıklı giriş sağlar',
    'membership.silver.feature2': 'VIP alanlarına erişim',
    'membership.silver.feature3': 'Rezervasyonlarda öncelik',
    'membership.silver.feature4': 'Seçili etkinliklerde özel avantajlar',
    'membership.silver.feature5': 'Üyelere özel duyurular ve içerikler',
    'membership.silver.feature6': 'Harcama limitlerinde %20 indirim',
    'membership.silver.feature7': 'Le Porte Restoran harcamalarında %10 indirim',
    'membership.gold.title': 'Diamond',
    'membership.gold.price': '599',
    'membership.gold.period': 'aylık',
    'membership.gold.feature1': 'MMBR\'ın en üst seviye üyelik statüsüdür',
    'membership.gold.feature2': 'Öncelikli giriş ve rezervasyon hakkı',
    'membership.gold.feature3': 'Evden MMBR\'a, MMBR\'dan eve ücretsiz VIP transfer',
    'membership.gold.feature4': 'Gelen DJ\'ler ile fotoğraf çekinme hakkı',
    'membership.gold.feature5': 'Doğrudan kişisel temsilci ile iletişime geçme',
    'membership.gold.feature6': 'VIP alanlarına erişim',
    'membership.gold.feature7': 'Özel masa ve lokasyon önceliği',
    'membership.gold.feature8': 'Etkinliklerde özel fiyatlandırma',
    'membership.gold.feature9': 'Sürpriz performans ve kapalı davetlere özel erişim',
    'membership.gold.feature10': 'Kişisel concierge / rezervasyon önceliği',
    'membership.gold.feature11': 'Harcama limitlerinde %30 indirim',
    'membership.gold.feature12': 'Aura Entertainment etkinliklerine ücretsiz katılım',
    'membership.gold.feature13': 'Le Porte Restoran harcamalarında %20 indirim',
    'membership.selectPlan': 'Üyeliği Başlat',
    'membership.selected': 'Seçildi ✓',
    'membership.benefits.title': 'Üye Avantajları',
    'membership.benefits.subtitle': 'Mmbr üyeleri için hazırlanmış özel avantajları keşfedin',
    'membership.benefits.reservation': 'Öncelikli Rezervasyon',
    'membership.benefits.reservationDesc': 'En iyi masaları öncelikli olarak ayırabilirsiniz',
    'membership.benefits.events': 'Özel Etkinlikler',
    'membership.benefits.eventsDesc': 'Sadece üyelere özel etkinliklere katılabilirsiniz',
    'membership.benefits.discounts': 'İndirimli Fiyatlar',
    'membership.benefits.discountsDesc': 'Tüm içecek ve yiyeceklerde özel üye indirimi',
    'membership.benefits.vip': 'VIP Hizmet',
    'membership.benefits.vipDesc': 'Kişisel hesap yöneticisi ve premium hizmet',
    'membership.success': '{planName} üyelik başvurunuz alındı! Ödeme sayfasına yönlendiriliyorsunuz.',
    'membership.error': 'Üyelik başvurusu gönderilirken bir hata oluştu. Lütfen tekrar deneyin.',
    'membership.selectPlanError': 'Lütfen bir üyelik planı seçin.',
    
    // Events Page
    'events.title': 'Yaklaşan Etkinlikler',
    'events.subtitle': 'Heyecan verici etkinliklerimizi kaçırmayın',
    'events.viewDetails': 'Detayları Görüntüle',
    'events.makeReservation': 'Rezervasyon Yap',
    'events.noEvents': 'Yaklaşan etkinlik bulunmuyor',
    'events.artist': 'Sanatçı',
    'events.genre': 'Tür',
    'events.duration': 'Süre',
    'events.close': 'Kapat',
    'events.hours': 'Saatler',
    
    // Event Descriptions
    'events.mahmutOrhan.desc': 'Dünya çapında ünlü DJ Mahmut Orhan ile unutulmaz bir gece geçirin. MMBR\'in benzersiz atmosferinde en iyi deep house ve elektronik müzik örneklerine dans etmeye hazırlanın.',
    'events.deepHouse.desc': 'En iyi deep house müzik örneklerinden oluşan bir gece. En iyi DJ\'lerle zemine inen müzik yolculuğunuza underground salonumuzda katılın.',
    'events.technoRevolution.desc': 'Teknoloji ve müzikün birleşimiyle dolu bir gece. Güçlü ritimler ve hipnotik melodielerle teknoloji ve müzikün birleşimini deneyin.',
    'events.electronicVibes.desc': 'VIP Lounge\'umuzda özel bir elektronik müzik deneyimi. Bu özel gece, seçkin misafirler için en sofistike formda elektronik müzik.',
    'events.underground.desc': 'Karanlık ve gizemli underground atmosferinde en underground sesleri keşfedin. Bu özel gece, alternatif elektronik müzikün en içten formunu yaşayacaksınız.',
    'events.ibiza.desc': 'MMBR\'de İbiza\'nın sihirli atmosferini yaşayın. Akdeniz manzara hissiyle bu özel gece, balearik ritimler ve batış hissiyle unutulmaz anlara sahip olacaksınız.',
    'events.minimal.desc': 'Minimalizm gücünü ve teknoloji enerjisini birleştiren bu özel gece, her ritimde anlamlı bir deneyim. Basitlik ve karmaşıklık arasındaki mükemmel dengenin keşfedildiği bir gece.',
    'events.progressive.desc': 'Progressive house müzikünün hayrete düşüren bir yolculuğuna çıkın. Ritimler ve melodi yapılarıyla dolu bu gece, müziksel bir yolculuğun deneyimini yaşayacaksınız.',
    
    // Admin Page
    'admin.title': 'Admin Paneli',
    'admin.reservations': 'Rezervasyonlar',
    'admin.messages': 'Mesajlar',
    'admin.events': 'Etkinlikler',
    'admin.users': 'Kullanıcılar',
    
    // Profile Page
    'profile.title': 'Profilim',
    'profile.personalInfo': 'Kişisel Bilgiler',
    'profile.reservations': 'Rezervasyonlarım',
    'profile.activeReservations': 'Aktif Rezervasyonlar',
    'profile.pastReservations': 'Geçmiş Rezervasyonlar',
    'profile.noActiveReservations': 'Aktif rezervasyonunuz bulunmuyor.',
    'profile.noPastReservations': 'Geçmiş rezervasyonunuz bulunmuyor.',
    'profile.membership': 'Üyelik Durumu',
    
    // Common
    'common.save': 'Kaydet',
    'common.cancel': 'İptal',
    'common.edit': 'Düzenle',
    'common.delete': 'Sil',
    'common.loading': 'Yükleniyor...',
    'common.submit': 'Gönder',
    'common.back': 'Geri',
    'common.next': 'İleri',
    'common.previous': 'Önceki',
    'common.close': 'Kapat',
    'common.confirm': 'Onayla',
    
    // Footer
    'footer.copyright': '© 2024 MMBR. Tüm hakları saklıdır.',
    'footer.social': 'Sosyal medyada takip edin',
  }
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'tr'>('en'); // Default to English, no localStorage

  // NO useEffect - NO localStorage access
  // NO automatic operations at startup
  // This prevents browser message interference

  const handleSetLanguage = (lang: 'en' | 'tr') => {
    setLanguage(lang);
    // Optional: Save to localStorage only when user explicitly changes language
    try {
      localStorage.setItem('mmbr-language', lang);
    } catch (e) {
      // Silent fail
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};